//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.MShopkeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.MShopkeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi xóa phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorDeleteFund {
            get {
                return ResourceManager.GetString("ErrorDeleteFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi sửa phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorEditFund {
            get {
                return ResourceManager.GetString("ErrorEditFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy hóa đơn thu nợ. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetBill {
            get {
                return ResourceManager.GetString("ErrorGetBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy danh sách nhân viên. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetEmployee {
            get {
                return ResourceManager.GetString("ErrorGetEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetFund {
            get {
                return ResourceManager.GetString("ErrorGetFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy chi tiết phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetFundDetail {
            get {
                return ResourceManager.GetString("ErrorGetFundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy danh sách phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetListFund {
            get {
                return ResourceManager.GetString("ErrorGetListFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy danh sách nhà cung cấp. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorGetSupplier {
            get {
                return ResourceManager.GetString("ErrorGetSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorNotify {
            get {
                return ResourceManager.GetString("ErrorNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lưu phiếu. Vui lòng liên hệ MISA để được giải quyết..
        /// </summary>
        internal static string ErrorSaveFund {
            get {
                return ResourceManager.GetString("ErrorSaveFund", resourceCulture);
            }
        }
    }
}
